apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-fs"
  namespace: "openshift-local-storage" 
spec:
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-0
  storageClassDevices:
    - storageClassName: "local-sc-fs" 
      forceWipeDevicesAndDestroyAllData: false 
      volumeMode: Filesystem
      fsType: xfs
      devicePaths: 
        - /path/to/device 
