kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.20 
      minVersion: 4.20.0
      maxVersion: 4.20.0
    graph: true 
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20 
      packages: 
       - name: aws-load-balancer-operator
       - name: 3scale-operator
       - name: node-observability-operator
  additionalImages: 
   - name: registry.redhat.io/ubi8/ubi:latest
