apiVersion: v1
kind: ConfigMap
metadata:
  name: attestation-policy
  namespace: trustee-operator-system
data:
  default.rego: |
    package policy

    import rego.v1

    # This policy validates multiple TEE platforms
    # The policy is meant to capture the TCB requirements
    # for confidential containers.

    # This policy is used to generate an EAR Appraisal.
    # Specifically it generates an AR4SI result.
    # More informatino on AR4SI can be found at
    # <https://datatracker.ietf.org/doc/draft-ietf-rats-ar4si/>

    # For the `executables` trust claim, the value 33 stands for
    # "Runtime memory includes executables, scripts, files, and/or
    #  objects which are not recognized."
    default executables := 33

    ##### SNP
    executables := 3 if {
      # In the future, we might calculate this measurement here various components
      input.snp.measurement in data.reference.measurement
    }
