- name: Create Rosa Account roles and operator roles
  hosts: localhost
  vars:
    prefix_for_name: project_name
    aws_region: ap-southeast-1
    openshift_cluster_name_suffix: xt1
    openshift_cluster_name: "{{ prefix_for_name }}-{{ openshift_cluster_name_suffix }}"
    openshift_major_version: "4.20"
    openshift_minor_version: 0
    openshift_version: "{{ openshift_major_version }}.{{ openshift_minor_version }}"
  tasks:

  - name: Get the current caller identity information
    amazon.aws.aws_caller_info:
    register: caller_info

  - name: Create Policy to assume Route53 Role
    amazon.aws.iam_managed_policy:
      policy_name: "{{ openshift_cluster_name }}-shared-vpc-route53-assume-role"
      policy: "{{ lookup('template','rosa-shared-vpc-route53.json.j2') }}"
      state: present
      tags:
        red-hat-managed: "true"
        hcp-shared-vpc: "true"

  - name: Create Policy to assume Endpoint Role
    amazon.aws.iam_managed_policy:
      policy_name: "{{ openshift_cluster_name }}-shared-vpc-endpoint-assume-role"
      policy: "{{ lookup('template','rosa-shared-vpc-endpoint.json.j2') }}"
      state: present
      tags:
        red-hat-managed: "true"
        hcp-shared-vpc: "true"

  - name: Create IAM role for HCP Installer
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-HCP-ROSA-Installer-Role"
      assume_role_policy_document: "{{ lookup('file','rosa-installer-policy.json') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_role_type: "installer"
        rosa_managed_policies: "true"
        rosa_role_prefix: "{{ openshift_cluster_name }}"
        rosa_openshift_version: "{{ openshift_major_version }}"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAInstallerPolicy
        - "arn:aws:iam::{{ caller_info.account }}:policy/{{ openshift_cluster_name }}-shared-vpc-route53-assume-role"
        - "arn:aws:iam::{{ caller_info.account }}:policy/{{ openshift_cluster_name }}-shared-vpc-endpoint-assume-role"

  - name: Create IAM role for ROSA HCP Support
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-HCP-ROSA-Support-Role"
      assume_role_policy_document: "{{ lookup('file','rosa-support-policy.json') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_role_type: "support"
        rosa_managed_policies: "true"
        rosa_role_prefix: "{{ openshift_cluster_name }}"
        rosa_openshift_version: "{{ openshift_major_version }}"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSASRESupportPolicy

  - name: Create IAM role for ROSA HCP Worker
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-HCP-ROSA-Worker-Role"
      assume_role_policy_document: "{{ lookup('file','rosa-worker-policy.json') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_role_type: "instance_worker"
        rosa_managed_policies: "true"
        rosa_role_prefix: "{{ openshift_cluster_name }}"
        operator_namespace: "{{ openshift_major_version }}"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAWorkerInstancePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  - name: Create ROSA HCP Operator IAM role for KMS
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-kube-system-kms-provider"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_kms_provider_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        operator_name: "kms-provider"
        rosa_managed_policies: "true"
        operator_namespace: "kube-system"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAKMSProviderPolicy

  - name: Create ROSA HCP Operator IAM role for Kube Controller
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-kube-system-kube-controller-manager"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_kube_controller_manager_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        operator_name: "kube-controller-manager"
        rosa_managed_policies: "true"
        operator_namespace: "kube-system"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAKubeControllerPolicy

  - name: Create ROSA HCP Operator IAM role for Image Registry
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-openshift-image-registry-installer-cloud-credentials"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_image_registry_installer_cloud_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_managed_policies: "true"
        operator_name: "installer-cloud-credentials"
        operator_namespace: "openshift-image-registry"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAImageRegistryOperatorPolicy

  - name: Create ROSA HCP Operator IAM role for Ingress Controller
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-openshift-ingress-operator-cloud-credentials"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_ingress_operator_cloud_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_managed_policies: "true"
        operator_name: "cloud-credentials"
        operator_namespace: "openshift-ingress-operator"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAIngressOperatorPolicy
        - arn:aws:iam::{{ caller_info.account }}:policy/{{ openshift_cluster_name }}-shared-vpc-route53-assume-role

  - name: Create ROSA HCP Operator IAM role for Capa Controller
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-kube-system-capa-controller-manager"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_capa_controller_manager_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_managed_policies: "true"
        operator_name: "capa-controller-manager"
        operator_namespace: "kube-system"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSANodePoolManagementPolicy

  - name: Create ROSA HCP Operator IAM role for Control Plane Operator
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-kube-system-control-plane-operator"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_control_plane_operator_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_managed_policies: "true"
        operator_name: "control-plane-operator"
        operator_namespace: "kube-system"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAControlPlaneOperatorPolicy
        - "arn:aws:iam::{{ caller_info.account }}:policy/{{ openshift_cluster_name }}-shared-vpc-route53-assume-role"
        - "arn:aws:iam::{{ caller_info.account }}:policy/{{ openshift_cluster_name }}-shared-vpc-endpoint-assume-role"

  - name: Create ROSA HCP Operator IAM role for EBS CSI Operator
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-openshift-cluster-csi-drivers-ebs-cloud-credentials"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_cluster_csi_drivers_ebs_cloud_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_managed_policies: "true"
        operator_name: "ebs-cloud-credentials"
        operator_namespace: "openshift-cluster-csi-driver"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSAAmazonEBSCSIDriverOperatorPolicy

  - name: Create ROSA HCP Operator IAM role for CNCO
    amazon.aws.iam_role:
      name: "{{ openshift_cluster_name }}-openshift-cloud-network-config-controller-cloud-creden"
      assume_role_policy_document: "{{ lookup('template','rosa-operator_cloud_network_config_controller_cloud_credentials_policy.json.j2') }}"
      tags:
        red-hat-managed: "true"
        rosa_hcp_policies: "true"
        rosa_managed_policies: "true"
        operator_name: "cloud-credentials"
        operator_namespace: "openshift-cloud-network-config-controller"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/ROSACloudNetworkConfigOperatorPolicy
