- name: Share Subnets with Another account to test ROSA in Shared VPC
  hosts: localhost
  vars:
    prefix_for_name: project_name
    aws_region: ap-southeast-1
    aws_egress_vpc_name: "{{ prefix_for_name }}-egress"
    aws_disconnected_vpc_name: "{{ prefix_for_name }}-disconnected"
    resource_share_name: rosa-share-subnet
    openshift_base_domain: example.com
    openshift_cluster_name_suffix: xt1
    openshift_cluster_name: "{{ prefix_for_name }}-{{ openshift_cluster_name_suffix }}"
  tasks:

  - name: Gather Information about Egress VPC
    amazon.aws.ec2_vpc_net_info:
      filters:
        "tag:Name": "{{ aws_egress_vpc_name }}"
      region: "{{ aws_region }}"
    register: egress_vpc_info

  - name: Query for any existing subnet(s) in Egress VPC
    amazon.aws.ec2_vpc_subnet_info:
      region: "{{ aws_region }}"
      filters:
        vpc-id:  "{{ egress_vpc_info.vpcs[0].vpc_id }}"
    register: egress_subnet_info

  - name: Gather Information about Disconnected VPC
    amazon.aws.ec2_vpc_net_info:
      filters:
        "tag:Name": "{{ aws_disconnected_vpc_name }}"
      region: "{{ aws_region }}"
    register: disconnected_vpc_info

  - name: Query for any existing subnet(s) in Disconnected VPC
    amazon.aws.ec2_vpc_subnet_info:
      region: "{{ aws_region }}"
      filters:
        vpc-id:  "{{ disconnected_vpc_info.vpcs[0].vpc_id }}"
    register: disconnected_subnet_info

  - name: Query for subnetID for AZ1 in Disconnected VPC
    amazon.aws.ec2_vpc_subnet_info:
      region: "{{ aws_region }}"
      filters:
        vpc-id:  "{{ disconnected_vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": "{{ aws_disconnected_vpc_name }}-subnet-az1"
    register: disconnected_subnet_info_az1

  - name: Query for subnetID for AZ2 in Disconnected VPC
    amazon.aws.ec2_vpc_subnet_info:
      region: "{{ aws_region }}"
      filters:
        vpc-id:  "{{ disconnected_vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": "{{ aws_disconnected_vpc_name }}-subnet-az2"
    register: disconnected_subnet_info_az2

  - name: Query for subnetID for AZ3 in Disconnected VPC
    amazon.aws.ec2_vpc_subnet_info:
      region: "{{ aws_region }}"
      filters:
        vpc-id:  "{{ disconnected_vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": "{{ aws_disconnected_vpc_name }}-subnet-az3"
    register: disconnected_subnet_info_az3

  - name: Create DNS route53 private domain 
    amazon.aws.route53_zone:
      vpc_id: "{{ disconnected_vpc_id }}"
      vpc_region: "{{ aws_region }}"
      zone: "{{ openshift_cluster_name }}.{{ openshift_base_domain }}" 
      state: present
    register: hosted_zone_info

  - name: Attach route53 private domain with Egress VPC
    shell: |
      aws route53 associate-vpc-with-hosted-zone \
       --hosted-zone-id {{ hosted_zone_info.zone_id }} \
       --vpc VPCRegion={{ aws_region }},VPCId={{ egress_vpc_id }} --region {{ aws_region }}

  - name: Share Subnet with specified AWS Account
    shell: |
      aws ram create-resource-share \
      --name "{{ resource_share_name }}" \
      --resource-arns "{{ disconnected_subnet_info_az1.subnets[0].subnet_arn }}" "{{ disconnected_subnet_info_az2.subnets[0].subnet_arn }}" "{{ disconnected_subnet_info_az3.subnets[0].subnet_arn }}" "{{ egress_subnet_info.subnets[0].subnet_arn }}" \
      --principals "{{ aws_account_number_to_share_with }}" \
      --allow-external-principals \
      --region "{{ aws_region }}"
    register: ram_share_status

  - name: Set Variable to use for instances
    set_stats:
      data:
        disconnected_subnet_id_a: "{{ disconnected_subnet_info_az1.subnets[0].subnet_id }}"
        disconnected_subnet_id_b: "{{ disconnected_subnet_info_az2.subnets[0].subnet_id }}"
        disconnected_subnet_id_c: "{{ disconnected_subnet_info_az3.subnets[0].subnet_id }}"
        disconnected_vpc_cidr: "{{ disconnected_vpc_info.vpcs[0].cidr_block }}"
        disconnected_vpc_id: "{{ disconnected_vpc_info.vpcs[0].vpc_id }}"
        egress_subnet_id_a: "{{ egress_subnet_info.subnets[0].subnet_id }}"
        egress_vpc_id: "{{ egress_vpc_info.vpcs[0].vpc_id }}"
        egress_vpc_cidr: "{{ egress_vpc_info.vpcs[0].cidr_block }}"
        hosted_zone_id_for_domain: "{{ hosted_zone_info.zone_id }}"