- name: Setup Bastion Node (Connected)
  hosts: bastion
  gather_facts: false
  remote_user: "{{ admin_username }}"
  vars_files:
    - vars/common.yaml
    - "vars/{{ cloud_provider }}.yaml"

  roles:
    - bastion_base

    - installer_prep_connected

    - role: hcp_provisioning
      when: hcp_cluster_suffixes is defined or (hcp_xacct_cluster_suffixes is defined and hcp_xacct_cluster_suffixes | length > 0)

    - role: letsencrypt_certs
      when: letsencrypt_enabled | default(false) | bool
