apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
spec:
  managementState: Managed

  # Actually evict pods.
  # Predictive only simulates.
  mode: Automatic

  # Run every 60 seconds for the test.
  deschedulingIntervalSeconds: 60

  profiles:
    # Rebalance pods according to topologySpreadConstraints
    - TopologyAndDuplicates

    # Required because hello-az uses emptyDir
    - EvictPodsWithLocalStorage

  # Restrict the test only to our demo namespace
  profileCustomizations:
    namespaces:
      included:
        - az-resilience-demo

  # Evict only one pod per descheduler cycle
  evictionLimits:
    total: 1
