apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: sputhenp-db1-zlw55
  name: sputhenp-db1-zlw55-infra-ap-southeast-1a 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: sputhenp-db1-zlw55 
      machine.openshift.io/cluster-api-machineset: sputhenp-db1-zlw55-infra-ap-southeast-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: sputhenp-db1-zlw55 
        machine.openshift.io/cluster-api-machine-role: infra 
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: sputhenp-db1-zlw55-infra-ap-southeast-1a 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: "node-role.kubernetes.io/infra"
          operator: "Exist"
          effect: "NoExecute"
      providerSpec:
        value:
          ami:
            id: ami-0e60320100241049a 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: sputhenp-db1-zlw55-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ap-southeast-1a
            region: ap-southeast-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - sputhenp-db1-zlw55-worker-sg 
          subnet:
            id: subnet-00e022a6bfe0d04c1 
          tags:
            - name: kubernetes.io/cluster/sputhenp-db1-zlw55 
              value: owned
          userDataSecret:
            name: worker-user-data
