- name: Setup Bastion Node
  hosts: bastion
  gather_facts: false
  remote_user: "{{ admin_username }}"
  vars_files:
    - vars/common.yaml
    - "vars/{{ cloud_provider }}.yaml"
  tasks:

  - name: Wait for SSH banners
    wait_for_connection:
      delay: 5
      timeout: 300

  - name: Gather hostname fact
    setup:
      gather_subset:
        - min
    when: mirror_registry_fqdn is not defined

  - name: Store mirror registry hostname
    set_fact:
      installer_quay_hostname: "{{ mirror_registry_fqdn | default(ansible_hostname) }}"

  - name: Install Required RPM Packages
    dnf:
      name: "{{ common_packages + cloud_extra_packages }}"
      state: present
    become: true

  - name: Cloud-specific setup (CLI, credentials, auth)
    include_tasks: "tasks/cloud-setup/{{ cloud_provider }}.yaml"

  - name: Enable mouse scrolling for tmux
    lineinfile:
      path: "{{ home_dir }}/.tmux.conf"
      line: "set -g mouse on"
      create: yes
      state: present

  - name: Add Terraform Yum Repo
    copy:
      dest: /etc/yum.repos.d/hashicorp.repo
      content: |
        [hashicorp]
        name=HashiCorp Stable - RHEL
        baseurl=https://rpm.releases.hashicorp.com/RHEL/9/$basearch/stable
        enabled=1
        gpgcheck=1
        gpgkey=https://rpm.releases.hashicorp.com/gpg
    become: true

  - name: Install Terraform
    dnf:
      name:
        - terraform
      state: present
    become: true

  - name: Create VNC User
    ansible.builtin.user:
      name: vncuser
    become: true

  - name: Listen for vnc server on port 5999
    ansible.builtin.lineinfile:
      path: /etc/tigervnc/vncserver.users
      insertafter: EOF
      line: ":99=vncuser"
    become: true

  - name: Copy squid Configuration file
    copy:
      src: squid.conf
      dest: /etc/squid/
    become: true

  - name: Copy squid allow list
    template:
      src: "{{ cloud_provider }}/squid-allow-list.txt.j2"
      dest: /etc/squid/squid-allow-list.txt
    become: true

  - name: Start and enable Squid
    systemd:
      state: started
      name: "{{ item }}"
      enabled: yes
    loop:
      - squid
    become: yes

  - name: Get the Mirror Registry, OC and OPM Tarball
    get_url:
      url: "{{ item }}"
      dest: "{{ home_dir }}/"
    loop: "{{ tarballs }}"

  - name: Unarchive Downloaded Tarballs
    unarchive:
      src: "{{ home_dir }}/{{ item }}"
      dest: "{{ home_dir }}/"
      remote_src: yes
    loop: "{{ tarball_basenames }}"

  - name: Copy CLI binaries to /usr/bin
    copy:
      src: "{{ home_dir }}/{{ item }}"
      dest: "/usr/bin/{{ item }}"
      remote_src: yes
      mode: 0755
    loop: "{{ cli_binaries }}"
    become: yes

  - name: Creates directory quay_root_mount
    file:
      path: "{{ quay_root_mount }}"
      state: directory
    become: true

  - name: Check if mirror registry is already running
    shell: |
      podman login -u init -p {{ mirror_registry_password }} {{ installer_quay_hostname }}:{{ mirror_registry_port }} 2>/dev/null
    register: registry_check
    ignore_errors: true
    changed_when: false

  - name: Install Mirror Registry
    shell: |
      {{ home_dir }}/mirror-registry install \
      --quayHostname {{ installer_quay_hostname }}:{{ mirror_registry_port }} \
      --quayRoot {{ quay_root_mount }} \
      --quayStorage {{ quay_root_mount }} \
      --initPassword {{ mirror_registry_password }}
    register: mirror_registry_install_output
    become: true
    when: registry_check.rc != 0

  - name: Copy Quay Root CA
    copy:
      src: "{{ quay_root_mount }}/quay-rootCA/rootCA.pem"
      dest: /etc/pki/ca-trust/source/anchors/
      remote_src: yes
      mode: 0644
    become: yes

  - name: Update CA trust Bundle
    shell: |
      update-ca-trust extract
    become: yes

  - name: Copy pull secret
    copy:
      dest: "{{ home_dir }}/pull-secret.txt"
      content: "{{ pull_secret }}"

  - name: Login to the registry and generate password
    shell: |
      podman login --authfile {{ home_dir }}/pull-secret.txt \
      -u init \
      -p {{ mirror_registry_password }} \
      {{ installer_quay_hostname }}:{{ mirror_registry_port }}

  - name: Create .docker Directory
    file:
      path: "{{ home_dir }}/.docker"
      state: directory

  - name: Copy pull secret to .docker directory
    copy:
      src: "{{ home_dir }}/pull-secret.txt"
      dest: "{{ home_dir }}/.docker/config.json"
      remote_src: yes

  - name: Store the mirror registry credentials to a variable
    shell: |
      CREDENTIAL=$(grep -A1 {{ installer_quay_hostname }} {{ home_dir }}/pull-secret.txt | grep -v {{ installer_quay_hostname }} | awk {'print $2'})
      echo $CREDENTIAL
    register: quay_credential

  - name: Copy ImageSet Configuration file
    template:
      src: "imageset-config.yaml.j2"
      dest: "{{ home_dir }}/imageset-config.yaml"
    when: registry_check.rc != 0

  - name: Create oc-mirror-output Directory
    file:
      path: "{{ home_dir }}/oc-mirror-output"
      state: directory
    when: registry_check.rc != 0

  - name: Mirror Images to the local registry
    shell: |
      oc mirror -c imageset-config.yaml --workspace file://oc-mirror-output/ docker://{{ installer_quay_hostname }}:{{ mirror_registry_port }} --v2
    when: registry_check.rc != 0

  - name: Check if install-dir already exists
    stat:
      path: "{{ home_dir }}/install-dir/manifests"
    register: install_dir_check

  - name: Check if cco-dir already exists
    stat:
      path: "{{ cco_dir }}/manifests"
    register: cco_dir_check

  - name: Check if openshift-install binary already exists
    stat:
      path: "{{ home_dir }}/openshift-install"
    register: openshift_install_check

  - name: Extract Openshift Install Binary from mirror registry
    shell: |
      oc adm release extract -a {{ pull_secret_location }} \
       --command=openshift-install "{{ installer_quay_hostname }}:{{ mirror_registry_port }}/{{ openshift_local_repository }}:{{ openshift_version }}-x86_64"
    when: not openshift_install_check.stat.exists

  - name: Create credentials/Install directory
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ home_dir }}/install-dir"
      - "{{ cco_dir }}"
    when: not install_dir_check.stat.exists

  - name: Extract ccoutils
    shell: |
      cd {{ cco_dir }}
      RELEASE_IMAGE=$({{ home_dir }}/openshift-install version | awk '/release image/ {print $3}')
      CCO_IMAGE=$(oc adm release info -a {{ home_dir }}/pull-secret.txt --image-for='cloud-credential-operator' $RELEASE_IMAGE)
      oc image extract $CCO_IMAGE --file="/usr/bin/ccoctl" -a {{ home_dir }}/pull-secret.txt
    when: not cco_dir_check.stat.exists

  - name: Changing permission of ccoutil to 755
    file:
      path: "{{ cco_dir }}/ccoctl"
      mode: 0755
    when: not cco_dir_check.stat.exists

  - name: Extract the list of CredentialsRequest objects from the OpenShift Container Platform release image
    shell: |
      cd {{ cco_dir }}
      RELEASE_IMAGE=$({{ home_dir }}/openshift-install version | awk '/release image/ {print $3}')
      oc adm release extract --credentials-requests \
      --cloud={{ cloud_provider }} \
      --to={{ cco_dir }}/credrequests \
      ${RELEASE_IMAGE}
    when: not cco_dir_check.stat.exists

  - name: Cloud-specific CCO/STS creation
    include_tasks: "tasks/cco/{{ cloud_provider }}.yaml"

  - name: Copy install-config.yaml
    template:
      src: "{{ cloud_provider }}/install-config.yaml.j2"
      dest: "{{ home_dir }}/install-config.yaml"
    when: not install_dir_check.stat.exists

  - name: Read Quay Root CA
    slurp:
      src: "{{ quay_root_mount }}/quay-rootCA/rootCA.pem"
    register: quay_root_ca
    become: true
    when: not install_dir_check.stat.exists

  - name: Append Quay Root CA to install-config.yaml
    blockinfile:
      path: "{{ home_dir }}/install-config.yaml"
      marker: ""
      insertafter: EOF
      block: "{{ quay_root_ca.content | b64decode | regex_replace('(?m)^', '    ') }}"
    when: not install_dir_check.stat.exists

  - name: Copy Install-config.yaml to install-dir
    copy:
      src: "{{ home_dir }}/install-config.yaml"
      dest: "{{ home_dir }}/install-dir/install-config.yaml"
      remote_src: yes
      mode: 0644
    when: not install_dir_check.stat.exists

  - name: Generate Manifests
    shell: |
      {{ home_dir }}/openshift-install create manifests --dir {{ home_dir }}/install-dir
    when: not install_dir_check.stat.exists

  - name: Copy CCO credentials to install-dir/manifests
    copy:
      src: "{{ cco_dir }}/manifests/"
      dest: "{{ home_dir }}/install-dir/manifests/"
      remote_src: yes
    when: not install_dir_check.stat.exists

  - name: Copy CCO tls files to install-dir/
    copy:
      src: "{{ cco_dir }}/tls"
      dest: "{{ home_dir }}/install-dir/"
      remote_src: yes
    when: not install_dir_check.stat.exists

  - name: Take a backup of the install-dir
    community.general.archive:
      path: "{{ home_dir }}/install-dir"
      dest: "{{ home_dir }}/install-dir-backup.bz2"
      format: bz2
    when: not install_dir_check.stat.exists

  - name: Cloud-specific helper scripts
    include_tasks: "tasks/scripts/{{ cloud_provider }}.yaml"
    when: lookup('fileglob', 'tasks/scripts/' + cloud_provider + '.yaml') | length > 0
