- name: Setup Bastion Node
  hosts: bastion
  gather_facts: false
  remote_user: "{{ admin_username }}"
  vars_files:
    - vars/common.yaml
    - "vars/{{ cloud_provider }}.yaml"

  roles:
    - bastion_base

    - mirror_registry

    - openshift_installer_prep

    - role: olm_catalog_suppression
      when: >
        hcp_cluster_suffixes is defined and hcp_cluster_suffixes | length > 0
        and olm_suppress_default_catalogs | default(false) | bool

    - hcp_provisioning