apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: openshift-config
data: 
  mirror-registry.hub.mylab.com..8443: | 
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
