apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators-proxy
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Operators (Proxy Cache)
  publisher: Red Hat
  sourceType: grpc
  image: quay-quay-quay-enterprise.apps.rosa.quay.2hhv.p3.openshiftapps.com/redhatio/redhat/redhat-operator-index:v4.20
  updateStrategy:
    registryPoll:
      interval: 24h