# Use rhcos layerd image with kata-containers rpm for coco installed
ARG RHCOS_COCO_IMAGE
FROM $RHCOS_COCO_IMAGE

ARG CA_CERTS_FILE
ARG REGISTRY_AUTH_FILE

ENV CA_CERTS_FILE=${CA_CERTS_FILE}
ENV REGISTRY_AUTH_FILE=${REGISTRY_AUTH_FILE}

WORKDIR /

COPY ${CA_CERTS_FILE} /
COPY ${REGISTRY_AUTH_FILE} /

RUN rm -f /envfile && \
    if [ ${CA_CERTS_FILE} ]; then \
        echo "CA_CERTS_FILE=/${CA_CERTS_FILE}" >> /envfile; \
    else \
        echo "CA_CERTS_FILE=" >> /envfile; \
    fi && \
    if [ ${REGISTRY_AUTH_FILE} ]; then \
        echo "REGISTRY_AUTH_FILE=/${REGISTRY_AUTH_FILE}" >> /envfile; \
    else \
        echo "REGISTRY_AUTH_FILE=" >> /envfile; \
    fi

# [Re]create initrd
RUN bash -c 'ls /lib/modules/*/vmlinu* | cut -d "/" -f 4 > /tmp/kernel_version' && \
    KVER=$(cat /tmp/kernel_version) && \
    . /envfile && \
    CA_CERTS=${CA_CERTS_FILE} REG_AUTH=${REGISTRY_AUTH_FILE} \
    CC_GUEST=1 IMAGE_TOPDIR=/usr/share/kata-containers \
    /usr/libexec/kata-containers/osbuilder/kata-osbuilder.sh -k ${KVER} 

RUN rpm-ostree cleanup -m && \
    ostree container commit
