apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: cluster
spec:
  domain: apps.clustername.domainname
  loadBalancer:
    platform:
      aws:
        type: Classic
      type: AWS
status:
  defaultPlacement: Workers
